definitions:
  steps:
    - step: &build
        name: Build
        caches:
          - docker
        name: Build Native Image
        image: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
        services:
          - docker
        size: 2x
        caches:
          - maven
        script:
          - cd tutorial/07-native-deployment
          - ./mvnw package -Pnative
        artifacts:
          - tutorial/07-native-deployment/target/*-runner

pipelines:
  branches:
    '*':
      - step: *build
     
