name: Quarkus Native Example Demo

run-name: ${{ github.actor }} is testing Quarkus Native Example 🚀

on: 
  push:
    paths: 
      - 'tutorial/07-native-deployment/**'

  pull_request:
    paths: 
      - 'tutorial/07-native-deployment/**'

jobs:
  Quarkus-Native-Build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
        options: --privileged
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      # - name: Set up JDK 17
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Native Image
        run: ./mvnw package -Pnative