name: Quarkus Native Example Demo

run-name: ${{ github.actor }} is testing Quarkus Native Example 🚀

on: [push, pull_request]
  # push:
  #   paths: 
  #     - 'tutorial/07-native-deployment/**'

  # pull_request:
  #   paths: 
  #     - 'tutorial/07-native-deployment/**'

jobs:
  Quarkus-Native-Build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
        options: --privileged
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # - name: Set up JDK 17
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Native Image
        run: |
          cd tutorial/07-native-deployment
          ./mvnw package -Pnative

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: native-image-runner
          path: tutorial/07-native-deployment/target/*-runner