name: Quarkus Native Example Demo

run-name: ${{ github.actor }} is testing Quarkus Native Example 🚀

on: [push, pull_request]
  # push:
  #   paths: 
  #     - 'tutorial/07-native-deployment/**'

  # pull_request:
  #   paths: 
  #     - 'tutorial/07-native-deployment/**'

jobs:
  Quarkus-Native-Build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Native Image
      run: |
        cd tutorial/07-native-deployment
        ./mvnw package -Pnative

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: native-image-runner
        path: tutorial/07-native-deployment/target/*-runner